### ISSUE TITLE
buildtools are in 30.0.3 but are expected to be in 30.0.2

### ISSUE THREAD

**Issue by vanous** [cs8898/docker-android-fdroid-sdk#1]
Hello @cs8898 , thank you very much for your work on this image. This has been very [useful for us](https://codeberg.org/Freeyourgadget/Gadgetbridge) and i presume for many others.
The recent changes are much appreciated: fdroidserver has been updated and apksigner doesn't need to be installed separately anymore... But buildtools which have been expected to be in 30.0.2 but are in fact in 30.0.3 , see the log below:

```
2022-07-25 22:41:09,094 CRITICAL: Unknown exception found!
166  Traceback (most recent call last):
167    File "/usr/local/bin/fdroid", line 22, in <module>
168      fdroidserver.__main__.main()
169    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/__main__.py", line 230, in main
170      raise e
171    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/__main__.py", line 211, in main
172      mod.main()
173    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/update.py", line 2372, in main
174      apks, cachechanged = process_apks(apkcache, repodirs[0], knownapks, options.use_date_from_apk)
175    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/update.py", line 1783, in process_apks
176      (skip, apk, cachethis) = process_apk(apkcache, apkfilename, repodir, knownapks,
177    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/update.py", line 1691, in process_apk
178      if not common.verify_apk_signature(apkfile):
179    File "/usr/local/lib/python3.10/dist-packages/fdroidserver/common.py", line 3506, in verify_apk_signature
180      output = subprocess.check_output(args + [apk])
181    File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
182      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
183    File "/usr/lib/python3.10/subprocess.py", line 501, in run
184      with Popen(*popenargs, **kwargs) as process:
185    File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
186      self._execute_child(args, executable, preexec_fn, close_fds,
187    File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
188      raise child_exception_type(errno_num, err_msg, err_filename)
189  FileNotFoundError: [Errno 2] No such file or directory: '/opt/android-sdk-linux/build-tools/30.0.2/apksigner'
```
For the test, i renamed the `/opt/android-sdk-linux/build-tools/30.0.3` to `/opt/android-sdk-linux/build-tools/30.0.2` to try that this would work and it indeed does work... does it work for you without this hack? Thank you once again.

**Comment by cs8898** [comment]
Ok i took me some Builds, but now it should be working... (will comment/close when i'm Sure)

The build is handled by TravisCI, so i added a BuildMatrix to also include the 30.0.2
(Also the Selected BuildTools are added to the PATH)

So the apksigner from path would be the 30.0.2

**Comment by vanous** [comment]
This is very awesome, thank you! Codeberg also does some caching (i think this is why it only surfaced now for us), so at some point our pipeline should break (as 30.0.2 would already exist). We run this CI task at midnight, but if you want me to run this earlier for test, let me know. I think i can also force it not to use the cache...

**Comment by cs8898** [comment]
should be working without any breaks...
Because you sould currently be on `latest`

When you are ready you can change your pipeline to the `30.0.2` tag, and remove your "mitigation" step.

See below Table to see installed BuildTools

| TAG | Installed Build Tools | BuildTool in Path |
|--|--|--|
| `latest` | `31.0.0` `30.0.3` | `31.0.0` |
| `31.0.0` | `31.0.0` `30.0.3` | `31.0.0` |
| `30.0.2` | `31.0.0` `30.0.3` `30.0.2` | `30.0.2` |

**Comment by vanous** [comment]
I can confirm that the 30.0.2 tag is working, thank you very much!

**Comment by vanous** [comment]
FYI, I have now realized one thing... i probably had an issue getting the apksigner to work correctly previously, so i provided a config line in the config.yml:

apksigner: /opt/android-sdk-linux/build-tools/30.0.2/apksigner

Which means, that most likely i can either remove it or adjust to `latest`... :)
